Update ci-kyc-report-front-end.yml

diff --git a/.github/workflows/ci-kyc-report-front-end.yml b/.github/workflows/ci-kyc-report-front-end.yml
--- a/.github/workflows/ci-kyc-report-front-end.yml
+++ b/.github/workflows/ci-kyc-report-front-end.yml
@@ -24,35 +24,38 @@ jobs:
         node-version: [20.x]
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
 
-    - name: Install dependencies
-      run: npm ci
+      - name: Verify package-lock.json exists
+        run: test -f package-lock.json || { echo "❌ package-lock.json missing"; exit 1; }
 
-    - name: Install Angular CLI
-      run: npm install -g @angular/cli
+      - name: Install dependencies
+        run: npm ci
 
-    - name: Build Angular project
-      run: npm run build -- --configuration=production
+      - name: Install Angular CLI
+        run: npm install -g @angular/cli
 
-    - name: Run tests
-      run: npm run test -- --watch=false --browsers=ChromeHeadless
+      - name: Build Angular project
+        run: npm run build -- --configuration=production
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.STAN_USERNAME }}
-        password: ${{ secrets.STAN_PASSWORD }}
+      - name: Run tests
+        run: npm run test -- --watch=false --browsers=ChromeHeadless
 
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v5
-      with:
-        context: ./kyc-report-front-end
-        push: true
-        tags: stanleyotieno/kyc-report-front-end:latest
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.STAN_USERNAME }}
+          password: ${{ secrets.STAN_PASSWORD }}
+
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v5
+        with:
+          context: ./kyc-report-front-end
+          push: true
+          tags: stanleyotieno/kyc-report-front-end:latest
